name: Build Gameflow Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:js-22.04

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
        with:
          persist-credentials: "true"

      - name: Checkout lfs
        run: |
          git lfs install --local
          AUTH=$(git config --local http.${{ forge.server_url }}/.extraheader)
          git config --local --unset http.${{ forge.server_url }}/.extraheader
          git config --local http.${{ forge.server_url }}/${{ forge.repository }}.git/info/lfs/objects/batch.extraheader "$AUTH"
          git lfs pull

      - name: Manual Bun Install
        run: |
          # Download and install via official script
          curl -fsSL https://bun.sh/install | bash

          # Manually add Bun to the PATH for subsequent steps
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

          # Force execution permissions just in case
          chmod +x $HOME/.bun/bin/bun

          # Verify it works immediately
          $HOME/.bun/bin/bun --version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Website
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          SITE_BASE: /
          SITE_URL: https://gameflow.simeonradivoev.com
        run: bun run build

      - name: Deploy
        uses: https://github.com/up9cloud/action-rsync@master
        env:
          HOST: simeonradivoev.com
          PORT: 8083
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /static_websites/gameflow
          SOURCE: ./dist/
          VERBOSE: true
          RUN_SCRIPT_ON: source
          USER: linuxserver.io
